//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace devexpExample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class devExpDenemeEntities : DbContext
    {
        public devExpDenemeEntities()
            : base("name=devExpDenemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Proje> Proje { get; set; }
        public virtual DbSet<Sozlesme> Sozlesme { get; set; }
        public virtual DbSet<Surec> Surec { get; set; }
        public virtual DbSet<veriGetir> veriGetir { get; set; }
        public virtual DbSet<veriGetir2> veriGetir2 { get; set; }
        public virtual DbSet<veriGetir3> veriGetir3 { get; set; }
    }
}
